# Using Git Action to update social links in profile automatically 
# ./.github/workflows/update-events.yml
name: Update events 
on: 
  schedule: 
  - cron: '0 0 * * *' 
  push:
    branches:
    - main
jobs: 
  update-social: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Social Readme 
      uses: zylele/social-readme@master 
      with: 
        blog_rss_link: http://sill-william.github.io/feeds/all.rss.xml
        blog_limit: 10 
        douban_name: sjx270992395
        douban_limit: 10